### ISSUE TITLE
setup script requires README file, but it does not exist

### ISSUE THREAD

**Issue by lowdef** [soundappraisal/soundannotatordemo#1]
Trying to run:
    soundannotatordemo/soundannotatordemo/democode/UseCase-ProcessingFiles.py

I get the error

    File "/home/lowdef/projects/soundannotatordemo/soundannotatordemo/democode/UseCase-ProcessingFiles.py", line 55, in <module>
    from  soundannotatordemo.config import runtimeMetaData

    ImportError: No module named soundannotatordemo.config

Trying to add on to the path does not fix the problem.

Trying to run:
    cd ~/projects/soundannotatordemo
    python  setup.py build install

gives:
```
lowdef@ubuntu:~/projects/soundannotatordemo$ python setup.py build install******************************************************************************
Warning: inconsistent subversion versions in working copy!
 GIT version: commit 2d0fd1d5862efb9f977b7845983ce6e0318717da
Author: RonaldAJ <r.a.j.van.elburg@pl.hanze.nl>
Date:   Mon May 15 16:38:24 2017 +0200

    Initial upload to public repository.
 

GIT status:
?? soundannotatordemo/config/runtimeMetaData.py

******************************************************************************

outputPathModifier='IrreproducibleResult_GIT_2d0fd1d5862efb9f977b7845983ce6e0318717da'

Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    long_description=read('README'),
  File "setup.py", line 11, in read
    return open(os.path.join(os.path.dirname(__file__), fname)).read()
IOError: [Errno 2] No such file or directory: 'README'
```

So I added a meaningless README file.

Tried again and added sudo:

```
lowdef@ubuntu:~/projects/soundannotatordemo$ sudo python setup.py build install

******************************************************************************
Warning: inconsistent subversion versions in working copy!
 GIT version: commit 2d0fd1d5862efb9f977b7845983ce6e0318717da
Author: RonaldAJ <r.a.j.van.elburg@pl.hanze.nl>
Date:   Mon May 15 16:38:24 2017 +0200

    Initial upload to public repository.
 

GIT status:
?? README
?? soundannotatordemo/config/runtimeMetaData.py

******************************************************************************

outputPathModifier='IrreproducibleResult_GIT_2d0fd1d5862efb9f977b7845983ce6e0318717da'

running build
...
```

Now it worked, but the README file was not used.

And warnings about " inconsistent subversion versions in working copy!" and something about "IrreproducibleResult". Meaningful or not?

**Comment by RonaldAJ** [comment]
This shouldn't happen if you have an actual clone of the git repo without uncommitted changes.  

Did you clone or download?

For now this is desired behavior. Working without git makes the work you do irreproducible.  I'll soon review how the calculated features are stored. That will be a good moment to consider a more deployment only like build.
